In [1]:
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout
import numpy as np

In [2]:
raw = pd.read_csv("RAW_recipes.csv")

In [3]:
raw

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7
1,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6
2,all in the kitchen chili,112140,130,196586,2005-02-25,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"['brown ground beef in large pot', 'add choppe...",this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13
3,alouette potatoes,59389,45,68585,2003-04-14,"['60-minutes-or-less', 'time-to-make', 'course...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,['place potatoes in a large pot of lightly sal...,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",11
4,amish tomato ketchup for canning,44061,190,41706,2002-10-25,"['weeknight', 'time-to-make', 'course', 'main-...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,['mix all ingredients& boil for 2 1 / 2 hours ...,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",8
...,...,...,...,...,...,...,...,...,...,...,...,...
231632,zydeco soup,486161,60,227978,2012-08-29,"['ham', '60-minutes-or-less', 'time-to-make', ...","[415.2, 26.0, 34.0, 26.0, 44.0, 21.0, 15.0]",7,"['heat oil in a 4-quart dutch oven', 'add cele...",this is a delicious soup that i originally fou...,"['celery', 'onion', 'green sweet pepper', 'gar...",22
231633,zydeco spice mix,493372,5,1500678,2013-01-09,"['15-minutes-or-less', 'time-to-make', 'course...","[14.8, 0.0, 2.0, 58.0, 1.0, 0.0, 1.0]",1,['mix all ingredients together thoroughly'],this spice mix will make your taste buds dance!,"['paprika', 'salt', 'garlic powder', 'onion po...",13
231634,zydeco ya ya deviled eggs,308080,40,37779,2008-06-07,"['60-minutes-or-less', 'time-to-make', 'course...","[59.2, 6.0, 2.0, 3.0, 6.0, 5.0, 0.0]",7,"['in a bowl , combine the mashed yolks and may...","deviled eggs, cajun-style","['hard-cooked eggs', 'mayonnaise', 'dijon must...",8
231635,cookies by design cookies on a stick,298512,29,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[188.0, 11.0, 57.0, 11.0, 7.0, 21.0, 9.0]",9,['place melted butter in a large mixing bowl a...,"i've heard of the 'cookies by design' company,...","['butter', 'eagle brand condensed milk', 'ligh...",10
231636,cookies by design sugar shortbread cookies,298509,20,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[174.9, 14.0, 33.0, 4.0, 4.0, 11.0, 6.0]",5,"['whip sugar and shortening in a large bowl , ...","i've heard of the 'cookies by design' company,...","['granulated sugar', 'shortening', 'eggs', 'fl...",7

In [4]:
calories = []
for i in raw.nutrition:
    s = i.split(", ")
    counter = 0
    for c in s:
        if counter ==0 :
            c = c.replace("[", '')
            c = c.replace("]", '')
            calories.append(c)
        counter+=1

In [5]:
raw["calories"] = calories

In [6]:
raw

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients,calories
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7,51.5
1,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6,173.4
2,all in the kitchen chili,112140,130,196586,2005-02-25,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"['brown ground beef in large pot', 'add choppe...",this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13,269.8
3,alouette potatoes,59389,45,68585,2003-04-14,"['60-minutes-or-less', 'time-to-make', 'course...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,['place potatoes in a large pot of lightly sal...,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",11,368.1
4,amish tomato ketchup for canning,44061,190,41706,2002-10-25,"['weeknight', 'time-to-make', 'course', 'main-...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,['mix all ingredients& boil for 2 1 / 2 hours ...,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",8,352.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
231632,zydeco soup,486161,60,227978,2012-08-29,"['ham', '60-minutes-or-less', 'time-to-make', ...","[415.2, 26.0, 34.0, 26.0, 44.0, 21.0, 15.0]",7,"['heat oil in a 4-quart dutch oven', 'add cele...",this is a delicious soup that i originally fou...,"['celery', 'onion', 'green sweet pepper', 'gar...",22,415.2
231633,zydeco spice mix,493372,5,1500678,2013-01-09,"['15-minutes-or-less', 'time-to-make', 'course...","[14.8, 0.0, 2.0, 58.0, 1.0, 0.0, 1.0]",1,['mix all ingredients together thoroughly'],this spice mix will make your taste buds dance!,"['paprika', 'salt', 'garlic powder', 'onion po...",13,14.8
231634,zydeco ya ya deviled eggs,308080,40,37779,2008-06-07,"['60-minutes-or-less', 'time-to-make', 'course...","[59.2, 6.0, 2.0, 3.0, 6.0, 5.0, 0.0]",7,"['in a bowl , combine the mashed yolks and may...","deviled eggs, cajun-style","['hard-cooked eggs', 'mayonnaise', 'dijon must...",8,59.2
231635,cookies by design cookies on a stick,298512,29,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[188.0, 11.0, 57.0, 11.0, 7.0, 21.0, 9.0]",9,['place melted butter in a large mixing bowl a...,"i've heard of the 'cookies by design' company,...","['butter', 'eagle brand condensed milk', 'ligh...",10,188.0
231636,cookies by design sugar shortbread cookies,298509,20,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[174.9, 14.0, 33.0, 4.0, 4.0, 11.0, 6.0]",5,"['whip sugar and shortening in a large bowl , ...","i've heard of the 'cookies by design' company,...","['granulated sugar', 'shortening', 'eggs', 'fl...",7,174.9

In [7]:
raw_filtered = raw.copy()

filters = (
 
    (raw_filtered['n_ingredients']<=11)
    &
    (raw_filtered['n_ingredients']>=6)
    )

raw_filtered = raw_filtered[filters]

In [8]:
raw_filtered

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients,calories
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7,51.5
1,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6,173.4
3,alouette potatoes,59389,45,68585,2003-04-14,"['60-minutes-or-less', 'time-to-make', 'course...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,['place potatoes in a large pot of lightly sal...,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",11,368.1
4,amish tomato ketchup for canning,44061,190,41706,2002-10-25,"['weeknight', 'time-to-make', 'course', 'main-...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,['mix all ingredients& boil for 2 1 / 2 hours ...,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",8,352.9
6,aww marinated olives,25274,15,21730,2002-04-14,"['15-minutes-or-less', 'time-to-make', 'course...","[380.7, 53.0, 7.0, 24.0, 6.0, 24.0, 6.0]",4,['toast the fennel seeds and lightly crush the...,my italian mil was thoroughly impressed by my ...,"['fennel seeds', 'green olives', 'ripe olives'...",9,380.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
231630,zydeco sauce,357451,15,461283,2009-02-23,"['15-minutes-or-less', 'time-to-make', 'course...","[239.9, 30.0, 19.0, 22.0, 1.0, 14.0, 5.0]",3,"['to make the sauce , combine the mayonnaise ,...",great sauce for cheeseburgers or dipping fries...,"['mayonnaise', 'prepared horseradish', 'worces...",6,239.9
231631,zydeco shrimp wrap,188810,57,37779,2006-10-03,"['60-minutes-or-less', 'time-to-make', 'course...","[482.6, 13.0, 25.0, 37.0, 33.0, 9.0, 27.0]",14,"['bring 3 quarts salted to water to a boil', '...",a wrap inspired by great cajun flavors,"['white rice', 'vegetable oil', 'onion', 'gree...",11,482.6
231634,zydeco ya ya deviled eggs,308080,40,37779,2008-06-07,"['60-minutes-or-less', 'time-to-make', 'course...","[59.2, 6.0, 2.0, 3.0, 6.0, 5.0, 0.0]",7,"['in a bowl , combine the mashed yolks and may...","deviled eggs, cajun-style","['hard-cooked eggs', 'mayonnaise', 'dijon must...",8,59.2
231635,cookies by design cookies on a stick,298512,29,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[188.0, 11.0, 57.0, 11.0, 7.0, 21.0, 9.0]",9,['place melted butter in a large mixing bowl a...,"i've heard of the 'cookies by design' company,...","['butter', 'eagle brand condensed milk', 'ligh...",10,188.0
231636,cookies by design sugar shortbread cookies,298509,20,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[174.9, 14.0, 33.0, 4.0, 4.0, 11.0, 6.0]",5,"['whip sugar and shortening in a large bowl , ...","i've heard of the 'cookies by design' company,...","['granulated sugar', 'shortening', 'eggs', 'fl...",7,174.9

In [9]:
raw_filtered['calories'] = pd.to_numeric(raw_filtered['calories'], errors='ignore')

In [10]:
#raw_filtered['calories'].describe()

In [11]:
#raw_filtered['calories'].hist(figsize=(8, 10), bins=300, xlabelsize=8, ylabelsize=8);

In [12]:
filters = (
 
    (raw_filtered['calories']<=600)
    &
    (raw_filtered['calories']>=100)
    )
    
raw_filtered = raw_filtered[filters]

In [13]:
raw_sampled = raw_filtered.copy()

In [14]:
raw_sampled = raw_sampled.sample(n=2000, random_state = 1)

In [15]:
raw_sampled

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients,calories
86142,french cheesecake,8117,45,35635,2000-03-13,"['60-minutes-or-less', 'time-to-make', 'course...","[158.3, 20.0, 19.0, 4.0, 7.0, 39.0, 2.0]",7,"['preheat the oven to 350 degrees f', 'in a la...",NaN,"['shortbread', 'cream cheese', 'french cheese'...",10,158.3
32869,buzzing bran muffins,177532,30,168087,2006-07-13,"['30-minutes-or-less', 'time-to-make', 'course...","[237.4, 12.0, 67.0, 14.0, 14.0, 5.0, 13.0]",10,"['grease a 12-cup muffin pan', 'preheat your o...",taken from piequeen.blogspot.com. they're ver...,"['boiling water', 'wheat bran', 'honey', 'cano...",11,237.4
218402,turkey wild rice pumpkin soup,315579,20,212497,2008-07-24,"['30-minutes-or-less', 'time-to-make', 'course...","[205.4, 13.0, 8.0, 18.0, 32.0, 17.0, 5.0]",7,"['cook and stir margarine , onions and celery ...",i found this recipe in the favorite brand name...,"['margarine', 'onion', 'celery', 'chicken brot...",10,205.4
127996,macaroni and cheese au gratin,178929,30,206101,2006-07-24,"['30-minutes-or-less', 'time-to-make', 'course...","[390.3, 32.0, 8.0, 14.0, 30.0, 65.0, 11.0]",14,['cook the macaroni according to package direc...,"from the book, caramel knowledge","['elbow macaroni', 'butter', 'onion', 'flour',...",11,390.3
225460,west african beans,15522,45,21738,2001-12-09,"['60-minutes-or-less', 'time-to-make', 'course...","[323.4, 14.0, 6.0, 3.0, 9.0, 6.0, 18.0]",14,"['in skillet , add oil , onion , garlic', 'coo...",i love this dish! my late husband was from ca...,"['onion', 'garlic clove', 'tomato paste', 'oli...",9,323.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
180712,sausage rice casserole,87654,55,122993,2004-03-28,"['60-minutes-or-less', 'time-to-make', 'course...","[402.4, 34.0, 6.0, 29.0, 34.0, 37.0, 10.0]",4,['mix all ingredients together in a 9 x 13 pan...,"another one from mom, kids","['pork sausage', 'onion', 'green bell pepper',...",10,402.4
124497,linda s kidney bean dip with crackers,222195,10,68526,2007-04-12,"['15-minutes-or-less', 'time-to-make', 'course...","[273.6, 15.0, 8.0, 15.0, 23.0, 28.0, 12.0]",5,"['mix garlic , onion , horseradish , dry musta...",i had a bean dip at one of my favorite restaur...,"['garlic cloves', 'onion', 'horseradish', 'dry...",7,273.6
173930,rich challah braided egg bread,103505,50,145451,2004-11-07,"['60-minutes-or-less', 'time-to-make', 'course...","[231.9, 11.0, 19.0, 10.0, 12.0, 6.0, 11.0]",16,['in bread machine add to bread pan in order s...,many challah breads either have too many eggs ...,"['water', 'eggs', 'oil', 'sugar', 'salt', 'flo...",8,231.9
39565,cheese sauce with flour,408105,15,1425905,2010-01-12,"['15-minutes-or-less', 'time-to-make', 'course...","[251.0, 29.0, 0.0, 27.0, 18.0, 59.0, 3.0]",6,"['in a small to medium-sized saucepan , melt b...",a cheesey sauce that can be used with differen...,"['butter', 'all-purpose flour', 'milk', 'chees...",7,251.0
95661,granny s cracklin bread,318334,35,37636,2008-08-08,"['60-minutes-or-less', 'time-to-make', 'course...","[225.6, 17.0, 0.0, 13.0, 10.0, 22.0, 8.0]",5,"['preheat oven to 425f', 'mix together cornmea...","recipe from crystal van poppe in her booklet ""...","['pork crackling', 'white cornmeal', 'self ris...",8,225.6

In [16]:
ingredients = set()
for i in raw_sampled.ingredients:
    s = i.split(", ")
    for c in s:
        c = c.replace("'", '')
        c = c.replace("[", '')
        c = c.replace("]", '')
        

        ingredients.add(c)

In [17]:
ingredients_pk = pd.read_pickle("ingr_map.pkl")  

ingredients_pk

,raw_ingr,raw_words,processed,len_proc,replaced,count,id
0,"medium heads bibb or red leaf lettuce, washed,...",13,"medium heads bibb or red leaf lettuce, washed,...",73,lettuce,4507,4308
1,mixed baby lettuces and spring greens,6,mixed baby lettuces and spring green,36,lettuce,4507,4308
2,romaine lettuce leaf,3,romaine lettuce leaf,20,lettuce,4507,4308
3,iceberg lettuce leaf,3,iceberg lettuce leaf,20,lettuce,4507,4308
4,red romaine lettuce,3,red romaine lettuce,19,lettuce,4507,4308
...,...,...,...,...,...,...,...
11654,soybeans,1,soybean,7,soybean,31,6702
11655,goose,1,goose,5,goose,8,3318
11656,ajwain,1,ajwain,6,ajwain,13,47
11657,brinjals,1,brinjal,7,brinjal,2,750
11658,khoya,1,khoya,5,khoya,6,4061

In [18]:
f = set()
for i in ingredients:
    i = ingredients_pk[ingredients_pk.raw_ingr == i]
    ing = ""
    counter = 0
    for i in i.replaced.to_string().split(" "):
        if counter != 0:
                ing+=" "
                ing+=i
        counter+=1
    f.add(ing)

name = pd.DataFrame(columns=f)
name

Empty DataFrame
Columns: [    cottage cheese,     carrot,     ravioli,     real butter,     graham cracker crust,     condensed tomato soup,     barbecue sauce,     marsala,     lean ground turkey,     ground chuck,     lime gelatin,     dried pink lentil,     cholesterol-free egg substitute,     enchilada sauce,     vegetable stock cube,     self raising flmy,     peach liqueur,     brown rice,     havarti cheese,     red enchilada sauce,     prime rib roast,     brewed coffee,     sesame oil,     caper,     instant tang orange drink,     whole chicken breast,     green apple,     mushroom cap,     chicken breast tender,     oregano,     broad egg noodle,     orzo pastum,     ground walnut,     dark raisin,     parmesan cheese,     apricot,     peppermint ice cream,     hoagie roll,     beef gravy,     peanut butter,     fresh oregano,     hormel real bacon bit,     cilantro,     chicken bouillon,     hot red pepper,     wondra flmy,     mild green chily,     venison tenderloin,     iced tea mix powder,     golden delicious apple,     fresh crabmeat,     medium egg noodle,     monterey jack cheese,     vanilla liqueur,     cognac,     soymilk,     fruit chutney,     turkey cutlet,     white truffle oil,     ground turkey,     salami,     salt,     dry lentil,     salted peanut,     winter squash,     rump roast,     phyllo pastry,     french fried onion ring,     cream of coconut,     salad potato,     tomato puree,     raspberry jam,     red bean,     tonic water,     pork chop,     dry mustard,     corn syrup,     fig,     salt & ground black pepper,     grape tomato,     dry sherry,     thai red curry paste,     snow pea,     taco shell,     eaglecondensed milk,     plain breadcrumb,     merlot,     canned tomato,     honey nut chex,     seasoned dry bread crumb,     pure maple syrup,     porterhouse steak,     ground mustard,     diced green chily,     bisquick,     frozen blueberry,     trout,     red bell pepper,     white vinegar,     lemon pepper, ...]
Index: []

[0 rows x 2077 columns]

In [19]:
for i in raw_sampled.ingredients:
    name.loc[len(name)] = 0
    s = i.split(", ")
    for c in s:
        c = c.replace("'", '')
        c = c.replace("[", '')
        c = c.replace("]", '')
        c = ingredients_pk[ingredients_pk.raw_ingr == c]

        c = c.replaced.to_string().split(" ")
        
        ing = ""
        counter = 0
        for i in c:
            if counter != 0:
                ing+=" "
                ing+=i
            counter+=1
        
        name.at[len(name)-1,ing]= 1

In [20]:
name

,cottage cheese,carrot,ravioli,real butter,graham cracker crust,condensed tomato soup,barbecue sauce,marsala,lean ground turkey,ground chuck,...,kidney bean,ature hot dog,mixed fruit,dry fettuccine,chocolate chip,tomato ketchup,portabella mushroom cap,pecan piece,evaporated skim milk,canned black bean
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1996,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
name = pd.read_csv("data.csv")
#create a csv file
#name.to_csv("data.csv", index=False, header=True)

In [ ]:
#name = name.drop(axis=1, columns='calories')

In [21]:
pd.set_option('display.max_columns', None)

In [22]:
list = []
for c in name.columns:
    #print(len(name[name[c] == 1]))
    if name[c].sum() < 100:
        list.append(c)

In [ ]:
#list

In [ ]:
#for i in list:
#    name = name[name[i] == 0]
#name

In [23]:
raw_sampled = raw_sampled.reset_index(drop=True)
calories_sampled = raw_sampled['calories']
#calories_sampled

In [24]:
name['calories'] = raw_sampled['calories']

In [25]:
name.drop(list, axis=1, inplace=True)

In [ ]:
#name.shape

In [26]:
name

,parmesan cheese,salt,baking soda,egg,pepper,water,garlic,salt and pepper,lemon juice,butter,all-purpose flmy,milk,sugar,garlic clove,olive oil,flmy,scallion,cream cheese,vanilla,tomato,sour cream,cheddar,cinnamon,baking powder,onion,vegetable oil,),brown sugar,chicken broth,calories
0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,158.3
1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,237.4
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,205.4
3,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,390.3
4,0,1,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,323.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,402.4
1996,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,273.6
1997,0,1,0,1,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,231.9
1998,0,1,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,251.0
1999,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,225.6

In [34]:
import pandas as pd
import numpy as np
import pydot
from math import ceil
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
from scipy.stats import chi2_contingency
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder, RobustScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import f1_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LassoCV
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from matplotlib import pyplot
from pprint import pprint
from sklearn.model_selection import GridSearchCV,  RandomizedSearchCV, cross_val_score, RepeatedStratifiedKFold
from sklearn import svm
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier, AdaBoostClassifier, StackingClassifier
from sklearn import metrics
from sklearn.model_selection import StratifiedKFold
import time
import imblearn
from imblearn.over_sampling import SMOTE
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

In [ ]:
target = name['calories']
data_train = name.drop('calories', axis=1)

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(data_train,target, test_size = 0.3, random_state = 0, shuffle = True)

In [ ]:
from sklearn.linear_model import LinearRegression
lin_model = LinearRegression()

In [ ]:
lin_model.fit(X_train, y_train)
labels_train = lin_model.predict(X_train)
labels_val = lin_model.predict(X_val)
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_val, labels_val))

In [ ]:
labels_val = pd.DataFrame (labels_val, columns= ['calories'])
labels_val['calories'] = pd.to_numeric(labels_val['calories'], errors='ignore')
labels_val.describe()

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout

In [ ]:
callback = tf.keras.callbacks.EarlyStopping(patience=3, restore_best_weights=True)

In [ ]:
model = Sequential()
model.add(Dense(8, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(16, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(1))

model.compile(optimizer='rmsprop',loss='mse',metrics=['mean_absolute_error'])
    
hist = model.fit(X_train,
              y_train,
              validation_split=0.2,
              epochs=100,
              batch_size=16,
              callbacks=[callback])

test_mse_score, test_mae_score = model.evaluate(X_val, y_val)

In [ ]:
print(f'Test MAE: {test_mae_score}')
			  
import matplotlib.pyplot as plt
loss_train = hist.history['mean_absolute_error']
loss_val = hist.history['val_mean_absolute_error']

epochs = range(1,93)
plt.plot(epochs, loss_train, 'g', label='Training MAE')
plt.plot(epochs, loss_val, 'b', label='Validation MAE')
plt.title('Training and Validation MAE')
plt.xlabel('Epochs')
plt.ylabel('Mean Absolute Error')
plt.legend()
plt.show()

loss_train = hist.history['loss']
loss_val = hist.history['val_loss']
epochs = range(1,93)
plt.plot(epochs, loss_train, 'g', label='Training loss')
plt.plot(epochs, loss_val, 'b', label='Validation loss')
plt.title('Training and Validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss (MSE)')
plt.legend()
plt.show()

In [ ]:
from sklearn.tree import DecisionTreeRegressor 
regressor = DecisionTreeRegressor(random_state = 0) 
regressor.fit(X_train, y_train)

In [ ]:
y_predict = regressor.predict(X_val)

In [ ]:
print(mean_absolute_error(y_val, y_predict))

In [ ]:
y_predict = pd.DataFrame (y_predict, columns= ['calories'])
y_predict['calories'] = pd.to_numeric(y_predict['calories'], errors='ignore')
y_predict.describe()

# Generating another random sample to use as a test

In [ ]:
raw_sampled_test = raw_sampled.sample(n=2000, random_state = 42)

In [ ]:
raw_sampled_test

In [ ]:
ingredients = set()
for i in raw_sampled_test.ingredients:
    s = i.split(", ")
    for c in s:
        c = c.replace("'", '')
        c = c.replace("[", '')
        c = c.replace("]", '')
        

        ingredients.add(c)

In [ ]:
f = set()
for i in ingredients:
    i = ingredients_pk[ingredients_pk.raw_ingr == i]
    ing = ""
    counter = 0
    for i in i.replaced.to_string().split(" "):
        if counter != 0:
                ing+=" "
                ing+=i
        counter+=1
    f.add(ing)

test = pd.DataFrame(columns=f)
test

In [ ]:
for i in raw_sampled_test.ingredients:
    test.loc[len(test)] = 0
    s = i.split(", ")
    for c in s:
        c = c.replace("'", '')
        c = c.replace("[", '')
        c = c.replace("]", '')
        c = ingredients_pk[ingredients_pk.raw_ingr == c]

        c = c.replaced.to_string().split(" ")
        
        ing = ""
        counter = 0
        for i in c:
            if counter != 0:
                ing+=" "
                ing+=i
            counter+=1
        
        test.at[len(test)-1,ing]= 1

In [ ]:
list = []
for c in test.columns:
    #print(len(name[name[c] == 1]))
    if test[c].sum() < 100:
        list.append(c)

In [ ]:
raw_sampled = raw_sampled.reset_index(drop=True)
calories_sampled = raw_sampled['calories']

In [ ]:
test['calories'] = raw_sampled['calories']

In [ ]:
test.drop(list, axis=1, inplace=True)

In [ ]:
test

In [ ]:
name = pd.read_csv("data.csv")
#create a csv file
#name.to_csv("data.csv", index=False, header=True)

In [ ]:
target_test = test['calories']
data_test = test.drop('calories', axis=1)

In [ ]:
labels_train = lin_model.fit(data_train)
labels_test = lin_model.predict(data_test)
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(target_test, labels_test))
labels_test = pd.DataFrame (labels_test, columns= ['calories'])
labels_test['calories'] = pd.to_numeric(labels_test['calories'], errors='ignore')
labels_test.describe()

In [ ]:
model = Sequential()
model.add(Dense(8, activation='relu', input_shape=(data_train.shape[1],)))
model.add(Dense(16, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(1))

model.compile(optimizer='rmsprop',loss='mse',metrics=['mean_absolute_error'])
    
hist = model.fit(data_train,
              target,
              validation_split=0.2,
              epochs=100,
              batch_size=16,
              callbacks=[callback])

test_mse_score, test_mae_score = model.evaluate(data_test, target_test)

In [ ]:
print(f'Test MAE: {test_mae_score}')
			  
import matplotlib.pyplot as plt
loss_train = hist.history['mean_absolute_error']
loss_val = hist.history['val_mean_absolute_error']

epochs = range(1,73)
plt.plot(epochs, loss_train, 'g', label='Training MAE')
plt.plot(epochs, loss_val, 'b', label='Validation MAE')
plt.title('Training and Validation MAE')
plt.xlabel('Epochs')
plt.ylabel('Mean Absolute Error')
plt.legend()
plt.show()

loss_train = hist.history['loss']
loss_val = hist.history['val_loss']
epochs = range(1,73)
plt.plot(epochs, loss_train, 'g', label='Training loss')
plt.plot(epochs, loss_val, 'b', label='Validation loss')
plt.title('Training and Validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss (MSE)')
plt.legend()
plt.show()

In [ ]:
regressor.fit(data_train, target)
y_pred_test = regressor.predict(data_test)
print(mean_absolute_error(target_test, y_pred_test))
y_pred_test = pd.DataFrame (y_pred_test, columns= ['calories'])
y_pred_test['calories'] = pd.to_numeric(y_pred_test['calories'], errors='ignore')
y_pred_test.describe()

In [ ]:
name

# transformar calorias em variÃ¡vel categÃ³rica

In [39]:
name_bin=name.copy()
name_bin['calories level']=""
for i in range(0, len(name_bin)): 
    if name_bin['calories'][i]>=350 and name_bin['calories'][i]<=600: 
        name_bin['calories level'][i]= '1' #1 Ã© saudÃ¡vel
    else: 
        name_bin['calories level'][i]= '0' #nÃ£o saudÃ¡vel
name_bin['calories level'].describe()

<ipython-input-39-16ed45140ca3>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  name_bin['calories level'][i]= '0' #nÃ£o saudÃ¡vel
<ipython-input-39-16ed45140ca3>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  name_bin['calories level'][i]= '1' #1 Ã© saudÃ¡vel

count     2000
unique       2
top          0
freq      1310
Name: calories level, dtype: object

In [45]:
name_bin['calories level'] = pd.to_numeric(name_bin['calories level'], errors='ignore')
target = name_bin['calories level']
data_train = name_bin.drop(['calories', 'calories level'], axis=1)

In [46]:
X_train, X_val, y_train, y_val = train_test_split(data_train,target, test_size = 0.3, random_state = 0, shuffle = True)

In [48]:
LG = LogisticRegression().fit(X_train,y_train)
labels_train = LG.predict(X_train)
labels_val = LG.predict(X_val)
print(f1_score(labels_train, y_train))
print(f1_score(labels_val, y_val))

0.17361111111111113
0.1589958158995816

In [49]:
LG = LogisticRegression().fit(X_train,y_train)
labels_train = LG.predict(X_train)
labels_val = LG.predict(X_val)
print(f1_score(labels_train, y_train))
print(f1_score(labels_val, y_val))

0.17361111111111113
0.1589958158995816

In [50]:
DT = DecisionTreeClassifier()
DT.fit(X = X_train, y = y_train)

DecisionTreeClassifier()

In [51]:
labels_train = DT.predict(X_train)
labels_val = DT.predict(X_val)
print(f1_score(labels_train, y_train))
print(f1_score(labels_val, y_val))

0.8160919540229885
0.33870967741935487

In [55]:
filters = (
 
    (raw_filtered['calories']<=600)
    &
    (raw_filtered['calories']>=350)
    )
    
Healthy_dishes = raw_filtered[filters].copy()

In [87]:
Dishes_Chosen = Healthy_dishes.sample(n=3)

In [88]:
print('Your dishes of the day are:')
print(Dishes_Chosen.iloc[0]['name'])
print(Dishes_Chosen.iloc[1]['name'])
print(Dishes_Chosen.iloc[2]['name'])
print('With a total amount of calories:')
print(Dishes_Chosen['calories'].sum())

Your dishes of the day are:
cheese enchiladas for oamc
corn cakes from readyville mill
grammie bea s scalloped potato and tuna casserole
With a total amount of calories:
1351.8